name: Deployment

on:
 workflow_dispatch:
   # Inputs the workflow accepts.
   inputs:
     version:
       description: 'Package version to deployed'
       required: true
       type: choice
       options:
         - "v1.0.20"
         - "v1.0.19"
         - "v1.0.18"
         - "v1.0.17"
         - "v1.0.16"
         - "v1.0.15"
         - "v1.0.14"
         - "v1.0.13"
         - "v1.0.12"
         - "v1.0.11"
         - "v1.0.10"
         - "v1.0.9"
         - "v1.0.8"
         - "v1.0.7"
         - "v1.0.6"
         - "v1.0.5"
         - "v1.0.4"
         - "v1.0.3"
         - "v1.0.2"
         - "v1.0.1"
         - "v1.0.0"
         - "v0.13.0"
         - "v0.12.1"
         - "v0.12.0"
         - "v0.11.2"
         - "v0.11.1"
         - "v0.11.0"
         - "v0.10.0"
         - "v0.9.0"
         - "v0.8.0"
         
     environment:
       description: 'Target Environment'
       required: true
       type: choice
       options:
         - dev
         - main
jobs:
 deployment:
   runs-on: ubuntu-latest
   name: "Deploying on : ${{ inputs.environment }}"
   steps:
     - run: echo release ${{ inputs.choice }} selected
