name: Preview - dev/stage/uat
on:
  pull_request:
    branches:
      - dev
      - stage
      - uat

permissions: write-all

env:
  VARI: hello/${{ github.ref_name }}

jobs:
  preview_build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
          echo $DE
          echo ${{ github.ref_name }}
          echo ${{ env.VARI }}
          echo ${{ github.head_ref }} - head
          echo ${{ github.base_ref }} - base
    env:
      DE: ${{ vars.DEPLOY_ENVIRONMENT }}
  semantic_version:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: show before changes
        run: cat ./k8s/helm/Chart.yaml

      - name: Set image tag
        run: |
          echo git describe --tags
          echo IMAGE_TAG=$(git describe --tags) >> $GITHUB_ENV
          sed -i "s/^appVersion:.*$/appVersion: $IMAGE_TAG/" ./k8s/helm/Chart.yaml
          echo $IMAGE_TAG
          cat ./k8s/helm/Chart.yaml

      - name: show after changes
        run: cat ./k8s/helm/Chart.yaml
