name: Preview - dev/stage/uat
on:
  push:
permissions: write-all

env:
  VARI: hello/${{ github.ref_name }}

jobs:
  preview_build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
          echo $DE
          echo ${{ github.ref_name }}
          echo ${{ env.VARI }}
          echo ${{ env.COND }}
    env:
      DE: ${{ vars.DEPLOY_ENVIRONMENT }}
      
