name: Preview
on:
  push:
permissions: write-all

jobs:
  preview_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches:
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
      
