name: Preview - dev/stage/uat
on:
  push:
    branches:
      - main
      - prod
      - dev
permissions: write-all

env:
  VARI: hello/${{ github.ref_name }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview_build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
          echo ${{ github.ref_name }}
          echo ${{ env.VARI }}
          echo ${{ env.COND }}
          env
    env:
      DE_JL: ${{ vars.DEPLOY_ENVIRONMENT }}
  semantic_version:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: show before changes
        run: cat ./k8s/helm/Chart.yaml

      - name: Set image tag
        run: |
          git describe --tags --abbrev=0
          echo IMAGE_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_ENV
          IMAGE_TAG=$(git describe --tags --abbrev=0)
          sed -i "s/^appVersion:.*$/appVersion: $IMAGE_TAG/" ./k8s/helm/Chart.yaml
          cat ./k8s/helm/Chart.yaml
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: show after changes
        run: |
          echo ${{ env.IMAGE_TAG }} - image tag
          cat ./k8s/helm/Chart.yaml
          echo ${{ env.VARI}}
      - name: pulumi version
        run: |
          responses=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/bee7ch7/aws/releases)
          echo $responses
          output=""
          for release in $(echo $responses | jq '.[] | .tag_name')
          do
             output+="- $release\n          "
          done
          echo $output
        env:
          GH_TOKEN: ${{ github.token }}
