name: Preview - dev/stage/uat
on:
  push:
    branches:
      - main
      - prod
      - dev
permissions: write-all

env:
  VARI: hello/${{ github.ref_name }}

jobs:
  preview_build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
          echo ${{ github.ref_name }}
          echo ${{ env.VARI }}
          echo ${{ env.COND }}
          env
    env:
      DE_JL: ${{ vars.DEPLOY_ENVIRONMENT }}
  semantic_version:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: show before changes
        run: cat ./k8s/helm/Chart.yaml

      - name: Set image tag
        run: |
          git describe --tags
          echo IMAGE_TAG=$(git describe --tags) >> $GITHUB_ENV
          echo $IMAGE_TAG
          sed -i "s/^appVersion:.*$/appVersion: $(git describe --tags)/" ./k8s/helm/Chart.yaml
          cat ./k8s/helm/Chart.yaml

      - name: show after changes
        run: |
          echo ${{ env.IMAGE_TAG }} - image tag
          cat ./k8s/helm/Chart.yaml
