name: Preview
on:
  push:
    branches:
      - main
      - prod
permissions: write-all
env:
  DE_WL: ${{ vars.DEPLOY_ENVIRONMENT }}
jobs:
  preview_build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo branches
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF}
          echo $DE
      - name: Separate deploy_environment
        run: |
          echo $DE_WL
          echo $DE_JL
    env:
      DE_JL: ${{ vars.DEPLOY_ENVIRONMENT }}
