name: Release

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      new_release:
        description: "New release is published ? True/False"
        value: ${{ jobs.release.outputs.new_release }}
      new_release_version:
        description: "New release version"
        value: ${{ jobs.release.outputs.new_release_version }} ####
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            @semantic-release/exec
            @saithodev/semantic-release-backmerge@2.2.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    outputs:
      new_release: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }} #
